### ISSUE TITLE
There is no data provider registered that can provide view data.

### ISSUE THREAD

**Issue by HebaruSan** [BrandonXLF/vscode-github-releases#1]
Hi @BrandonXLF, this is a really neat idea for an extension!

However, when I install it, it just says this:

![image](https://github.com/BrandonXLF/vscode-github-releases/assets/1559108/06db9f3e-d862-4751-90f8-bbdfcec1eed8)

If I click the reload icon, I get this notification:

![image](https://github.com/BrandonXLF/vscode-github-releases/assets/1559108/393daae7-0193-48db-aab2-b2a819f0386e)

Any idea if I can somehow get it working?

Thanks!

**Comment by BrandonXLF** [comment]
Hi @HebaruSan,

The extension should be working, so I'm not sure what the problem is. If you go to Help > Toggle Developer Tools do you see any errors related to the extension?

**Comment by HebaruSan** [comment]
Huh, yes, the last exception in the console has your name on it! Something about parsing a URL:

![image](https://github.com/BrandonXLF/vscode-github-releases/assets/1559108/eade1064-9636-4e60-b703-b90a9089c3de)

I haven't done any vscode extension dev, unfortunately. Let me know if there's a way I can get you a full stack trace on that.

**Comment by HebaruSan** [comment]
_Maybe_ this one?

https://github.com/BrandonXLF/vscode-github-releases/blob/5379224e5f2358741846503f14297b7d0332650c/src/ReleaseProvider.ts#L119

Checking our releases, I don't see `authorIcon` defined anywhere:

- <https://api.github.com/repos/KSP-CKAN/CKAN/releases>

**Comment by BrandonXLF** [comment]
@HebaruSan It seems to be an error when activating the extension, so I don't think any code is run before the error is raised. Can you try fully uninstalling the extension and then reinstalling it from https://github.com/BrandonXLF/vscode-github-releases/releases/tag/v1.2.0?

**Comment by HebaruSan** [comment]
Hi @BrandonXLF, sure...

OK, I've removed it and installed from that download. There is no change; everything in the description in the OP here still looks exactly the same. Cheers!

**Comment by BrandonXLF** [comment]
@HebaruSan What version of VS Code do you have installed?

**Comment by HebaruSan** [comment]
The latest one, I believe:

![image](https://github.com/BrandonXLF/vscode-github-releases/assets/1559108/8876bf85-ee90-4ce0-87b2-1db576b6f545)

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:33:48.698Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.8.0-36-generic

**Comment by BrandonXLF** [comment]
Huh. The only difference between our installations is the OS. @HebaruSan Can you try installing [this version](https://github.com/user-attachments/files/16021185/GitHub.Releases.zip)? I removed all the URLs from the package.json file.

**Comment by HebaruSan** [comment]
> Huh. The only difference between our installations is the OS.

I guess it's possible that something platform dependent is going on...?

> @HebaruSan Can you try installing [this version](https://github.com/user-attachments/files/16021185/GitHub.Releases.zip)? I removed all the URLs from the package.json file.

Done. No change.

**Comment by BrandonXLF** [comment]
Weird. Does the same error show up in the console?

**Comment by HebaruSan** [comment]
Yup, and now there's more of a semblance of a stack trace (but with obfuscated function names):

![image](https://github.com/BrandonXLF/vscode-github-releases/assets/1559108/b54056ed-e9a6-402b-a24b-32faef7d7667)

This time I noticed that the error appears when I click the extension's icon in the toolbar, not at startup, in case that helps.

**Comment by BrandonXLF** [comment]
Can you try [installing the Insiders version](https://code.visualstudio.com/insiders/#linux) and installing the extension there?

**Comment by HebaruSan** [comment]
> Can you try [installing the Insiders version](https://code.visualstudio.com/insiders/#linux) and installing the extension there?

Hmm, I haven't heard of this. What is it, and why do you think it would help here? I'm happy to swap out versions of an extension that isn't working anyway, but I'd rather not go messing around with software that I rely upon unless there's a good reason.

**Comment by BrandonXLF** [comment]
> > Can you try [installing the Insiders version](https://code.visualstudio.com/insiders/#linux) and installing the extension there?
> 
> Hmm, I haven't heard of this. What is it, and why do you think it would help here? I'm happy to swap out versions of an extension that isn't working anyway, but I'd rather not go messing around with software that I rely upon unless there's a good reason.

It's so we can have a separate installation of VS Code without messing with your main installation. It's able to be installed side-by-side with your current installation.

**Comment by HebaruSan** [comment]
Alright, I have the Insiders vscode now. Which version of the extension would you like me to try?

**Comment by BrandonXLF** [comment]
@HebaruSan The one from the extension store

**Comment by HebaruSan** [comment]
OK, got it set up. What do you want me to try now?

![image](https://github.com/BrandonXLF/vscode-github-releases/assets/1559108/285ae12d-e786-4fd7-9c97-6b8c1f1fb066)

(The error in the console is identical, including the stack trace.)

**Comment by BrandonXLF** [comment]
@HebaruSan I was hoping using a fresh install would resolve the error. What OS are you using? I'm going to try to see if I can reproduce the error on my end.

**Comment by BrandonXLF** [comment]
Feel free to reopen this issue if it still persists
