### ISSUE TITLE
"Latest" and "Pre-Release" flags seem to be mutually exclusive

### ISSUE THREAD

**Issue by K3nny567** [BrandonXLF/vscode-github-releases#2]
The flags for setting a release as the latest and as a pre-release seem to be mutually exclusive, with `pre-release` overriding `latest`.

ie: A release can not be flagged as both, the website completely ignores `latest` if the release is a `pre-release` and doesn't even provide the options to flag as both, just `pre-release`, unless the release is the latest.

The website even toggles the checkbox for `latest` when you toggle the checkbox for `pre-release`. ie: It never lets you have both checked.

**Comment by BrandonXLF** [comment]
Thank you for bringing this issue to my attention! It is fixed as of v1.3.0.
